
<div id="header">
	<div class="navbar">
		<div class="navbar-inner">
		  <div class="container">
			<a class="brand" href="#">3mik.com...</a>
		
		
			<ul class="nav">
				<li class="active">
				  <a href="http://www.3mik.com">Home</a>
				</li>
				<li><a href="/test/ful/single.php">Share</a></li>
				<li><a href="/qa/ask.php">Ask</a></li>
				<li class="divider-vertical"></li>
				<li><a href="/user/login.php">login</a></li>
			</ul> <!-- fixed links -->
			
		  </div>
		</div>
	</div> <!-- navbar -->
</div> <!-- header -->

