
<div id="header">
	<div class="navbar">
		<div class="navbar-inner">
		  <div class="container">
			<a class="brand" href="/">3mik.com	<span class="beta">BETA</span> </a>

			<ul class="nav">
				<li class="active">
				  <a href="/">Home</a>
				</li>
				<li><a href="/share/new.php">Share</a></li>
				<li><a href="/qa/new.php">Ask</a></li>
				<li class="divider-vertical"></li>
				<li><a href="/user/login.php">login</a></li>
			</ul> <!-- fixed links -->
			
			<form>
				<input id="site-search" name="s" type="text" class="search-query" placeholder="Search">
			</form>
			
		  </div>
		</div>
	</div> <!-- navbar -->
</div> <!-- header -->

