
<div id="header">
	<div class="h-content">
		<div rel="home" id="logo">
				<h3> <a href="/"> <img src="/css/images/logo.png" alt="logo" /> </a> </h3>
		</div>
       
		<div id="hcenter">
				<div id="login">
				 <span class="register"><a href="/">Home</a></span>
				 &nbsp;|&nbsp
				 <span class="register"><a href="/user/logout.php">Logout</a></span>
				  &nbsp;|&nbsp
				 <span class="register"><a href="/user/dashboard.php">My Account</a></span>
				 &nbsp;(<?php echo $gSessionUser->firstName; ?>)
				</div>
				
		</div>

	</div>
</div>
