
<div id="footer">
	<div class="f-content">
		<div id="f-menu" class="floatl">
			<ul>
				<li><a href="#"> Feedback </a> |</li>
				<li><a href="#"> FAQ </a> |</li>
				<li><a href="#"> Blog </a></li>
			</ul>
			</div>
			<div id="social" class="floatr">
				<a class="fb" href="#Facebook"></a>
				<a class="tw" href="#Twitter"></a>
				<a class="yt" href="#YouTube"></a>
			</div>
			<div class="clear"></div>
		<div id="copyright"> Copyright © 2011 Your Logo </div>
	</div>
</div>