<div id="left-panel">
     <div style="border-bottom: 1px solid #ccc;padding:10px;">

        <a href="/"> Home </a>

    </div>

    <div style="border-bottom: 1px solid #ccc;padding:10px;">
        <p>To post a job you need a company account. </p>
        <a href="/opening/create.php"> Post your job </a>

    </div>


    <div style="border-bottom: 1px solid #ccc;padding:10px;">
        <p> Access company dashboard to view applications for posted jobs. </p>
        <a href="/opening/list.php"> Company dashboard</a>
    </div>

</div>

