
<div id="head">
    <h3> 3mik.com - Ask and get answers</h3>
    <div id="search-top">
        <form method="get" id="searchform" action="">	
                <input type="text" onblur="if (this.value == '') {this.value = 'Search';}" onfocus="if (this.value == 'Search') {this.value = '';}" value="Search" class="text" name="s" id="s"> 
                <input type="image" class="but" src="/css/images/search-btn.png" value=" ">
                
        </form>
				
	</div>
</div>

<div class="bbd5"></div>