<img src="/css/images/head-bg.jpg" />
<div id="head" class="yui3-g">
    
    <div class="yui3-u-1-2">
        <h3> 3mik.com - Discover and Share</h3>
    </div>
    <div id="search-top" class="yui3-u-1-2">
        <form method="get" id="searchform" action="">	
                <input type="text" onblur="if (this.value == '') {this.value = 'Search';}" onfocus="if (this.value == 'Search') {this.value = '';}" value="Search" class="text" name="stoken" id="s"> 
                <input type="image" class="but" src="/css/images/search-btn.png" value=" ">
                
        </form>
				
	</div>
</div>

<div class="bbd5"></div>