
<div class="p20 mt20">
    <h2> <a href="/user/interests.php"> My Interests &raquo;<a/> </h2>
    
        
    <h2> Locations</h2>
    <hr>
    <div class="sidebar-box">
        <ul>
            <li> <a href="/?stoken=Bangalore&ft=l"> Bangalore </a> </li>
            <li> <a href="/?stoken=Calcutta&ft=l">Calcutta </a> </li>
            <li> <a href="/?stoken=Chennai&ft=l">Chennai </a> </li>
            <li> <a href="/?stoken=Delhi&ft=l"> Delhi </a> </li>
            <li> <a href="/?stoken=Mumbai&ft=l"> Mumbai </a> </li>
        </ul>
    </div>
    
    <h2> Brands</h2>
    <hr>
    <div class="sidebar-box">
        <ul>
            <li> <a href="/?stoken=Nokia&ft=b"> Nokia </a> </li>
            <li> <a href="/?stoken=Samsung&ft=b">Samsung </a> </li>
            <li> <a href="/?stoken=V-Gaurd&ft=b">V-Gaurd </a> </li>
            <li> <a href="/?stoken=24hourloot.com&ft=b"> 24hourloot.com </a> </li>
            
        </ul>
    </div>

</div>



