
<div id="sidebar">
    <div class="block">
        <p>
            What is a good story? Something that is interesting and not known to
            many. You like it and want to share it with the world.
        </p>
        <p>
            Story link is required. Please consider using a URL shortening service like
            <b> goog.gl </b> for very long URL.
            <br/>
            <br/>
            We encourage you to share your name/email to get credit for your submissions.
            However you can do  anonymous submissions as well.
        </p>
        <p>
            Apologies for including Captcha. We do not know of any other way to stop
            spam bots here!
        </p>
        
    </div>
</div>



