
<div id="sidebar">
    <div class="block">
        <p>
            What is a good story? Something that is interesting and not known to
            many. You like it and want to share it with the world.
        </p>
        <p>
            Title can only be alphanumeric. You can include html tags like
            &lt;p&gt; and &lt;img /&gt; etc. in the post description and summary.
        </p>
        <p>
            Use Add Link and Add Image buttons to add links and images to your story.
        </p>
    </div>
</div>



