
<div id="sidebar">
    <div class="highlight">
        <p>
           <b> Why we need your email? </b>
			we need your email to  identify you on our site. We respect your privacy
			and do not display or use your email in any other way.
        </p>
        <p>
            <b> What is a good password? </b>
			A Good password should be hard to guess for people who know you.
			Do not use proper nouns or dictionary words.
        </p>
        
    </div>
</div>

