
<div id="sidebar">
    <div class="highlight">
        <p>
           <b> What is a good question? </b>
			Please be specific. A focused and on the topic question has a better chance
			to get answered. 
        </p>
        <p>
            <b> Why should I include my location? </b>
			People can suggest answers or places that will be near your place or inside your city.
			That would help you narrow down the suggestions.
        </p>
        <p>
            <b> How many tags? </b>
			Including a lot of tags is not needed. Think of keywords that can help
			Others locate this question quickly. Again, please be specific.
        </p>
		<p>
            <b> Add link </b>
			You can add links from other websites and sources.
        </p>

    </div>
</div>

